/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl.impl;

import com.zenika.aicdsl.AicdslPackage;
import com.zenika.aicdsl.Click;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.impl.ClickImpl#getButtonName <em>Button Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClickImpl extends ActionImpl implements Click
{
  /**
   * The default value of the '{@link #getButtonName() <em>Button Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getButtonName()
   * @generated
   * @ordered
   */
  protected static final String BUTTON_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getButtonName() <em>Button Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getButtonName()
   * @generated
   * @ordered
   */
  protected String buttonName = BUTTON_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClickImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AicdslPackage.Literals.CLICK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getButtonName()
  {
    return buttonName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setButtonName(String newButtonName)
  {
    String oldButtonName = buttonName;
    buttonName = newButtonName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AicdslPackage.CLICK__BUTTON_NAME, oldButtonName, buttonName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AicdslPackage.CLICK__BUTTON_NAME:
        return getButtonName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AicdslPackage.CLICK__BUTTON_NAME:
        setButtonName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AicdslPackage.CLICK__BUTTON_NAME:
        setButtonName(BUTTON_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AicdslPackage.CLICK__BUTTON_NAME:
        return BUTTON_NAME_EDEFAULT == null ? buttonName != null : !BUTTON_NAME_EDEFAULT.equals(buttonName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (buttonName: ");
    result.append(buttonName);
    result.append(')');
    return result.toString();
  }

} //ClickImpl
