/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl.impl;

import com.zenika.aicdsl.AicdslPackage;
import com.zenika.aicdsl.Gps;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gps</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.impl.GpsImpl#getLat <em>Lat</em>}</li>
 *   <li>{@link com.zenika.aicdsl.impl.GpsImpl#getLon <em>Lon</em>}</li>
 *   <li>{@link com.zenika.aicdsl.impl.GpsImpl#getAlti <em>Alti</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GpsImpl extends ActionImpl implements Gps
{
  /**
   * The default value of the '{@link #getLat() <em>Lat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLat()
   * @generated
   * @ordered
   */
  protected static final float LAT_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getLat() <em>Lat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLat()
   * @generated
   * @ordered
   */
  protected float lat = LAT_EDEFAULT;

  /**
   * The default value of the '{@link #getLon() <em>Lon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLon()
   * @generated
   * @ordered
   */
  protected static final float LON_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getLon() <em>Lon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLon()
   * @generated
   * @ordered
   */
  protected float lon = LON_EDEFAULT;

  /**
   * The default value of the '{@link #getAlti() <em>Alti</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlti()
   * @generated
   * @ordered
   */
  protected static final float ALTI_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getAlti() <em>Alti</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlti()
   * @generated
   * @ordered
   */
  protected float alti = ALTI_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GpsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AicdslPackage.Literals.GPS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public float getLat()
  {
    return lat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLat(float newLat)
  {
    float oldLat = lat;
    lat = newLat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AicdslPackage.GPS__LAT, oldLat, lat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public float getLon()
  {
    return lon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLon(float newLon)
  {
    float oldLon = lon;
    lon = newLon;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AicdslPackage.GPS__LON, oldLon, lon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public float getAlti()
  {
    return alti;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAlti(float newAlti)
  {
    float oldAlti = alti;
    alti = newAlti;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AicdslPackage.GPS__ALTI, oldAlti, alti));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AicdslPackage.GPS__LAT:
        return getLat();
      case AicdslPackage.GPS__LON:
        return getLon();
      case AicdslPackage.GPS__ALTI:
        return getAlti();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AicdslPackage.GPS__LAT:
        setLat((Float)newValue);
        return;
      case AicdslPackage.GPS__LON:
        setLon((Float)newValue);
        return;
      case AicdslPackage.GPS__ALTI:
        setAlti((Float)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AicdslPackage.GPS__LAT:
        setLat(LAT_EDEFAULT);
        return;
      case AicdslPackage.GPS__LON:
        setLon(LON_EDEFAULT);
        return;
      case AicdslPackage.GPS__ALTI:
        setAlti(ALTI_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AicdslPackage.GPS__LAT:
        return lat != LAT_EDEFAULT;
      case AicdslPackage.GPS__LON:
        return lon != LON_EDEFAULT;
      case AicdslPackage.GPS__ALTI:
        return alti != ALTI_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (lat: ");
    result.append(lat);
    result.append(", lon: ");
    result.append(lon);
    result.append(", alti: ");
    result.append(alti);
    result.append(')');
    return result.toString();
  }

} //GpsImpl
