/*
 * generated by Xtext 2.10.0
 */
package com.zenika.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAicdslScopeProvider extends DelegatingScopeProvider {
}
