/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.zenika.aicdsl.AicdslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
} // Action
