/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.zenika.aicdsl.AicdslFactory
 * @model kind="package"
 * @generated
 */
public interface AicdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "aicdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.zenika.com/Aicdsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "aicdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AicdslPackage eINSTANCE = com.zenika.aicdsl.impl.AicdslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.DslImpl <em>Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.DslImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getDsl()
   * @generated
   */
  int DSL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DSL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.TypeImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.FeatureImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TITLE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Scenarios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__SCENARIOS = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.ScenarioImpl <em>Scenario</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.ScenarioImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getScenario()
   * @generated
   */
  int SCENARIO = 3;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__TITLE = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Scenario</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCENARIO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.ActionImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getAction()
   * @generated
   */
  int ACTION = 4;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.SensorImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 5;

  /**
   * The feature id for the '<em><b>Sensor Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SENSOR_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TITLE = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.BatteryImpl <em>Battery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.BatteryImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getBattery()
   * @generated
   */
  int BATTERY = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BATTERY__VALUE = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Battery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BATTERY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.GpsImpl <em>Gps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.GpsImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getGps()
   * @generated
   */
  int GPS = 7;

  /**
   * The feature id for the '<em><b>Lat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GPS__LAT = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GPS__LON = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alti</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GPS__ALTI = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Gps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GPS_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.ClickImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getClick()
   * @generated
   */
  int CLICK = 8;

  /**
   * The feature id for the '<em><b>Button Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__BUTTON_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.zenika.aicdsl.impl.RunImpl <em>Run</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zenika.aicdsl.impl.RunImpl
   * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getRun()
   * @generated
   */
  int RUN = 9;

  /**
   * The feature id for the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN__APP_NAME = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Run</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUN_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Dsl <em>Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dsl</em>'.
   * @see com.zenika.aicdsl.Dsl
   * @generated
   */
  EClass getDsl();

  /**
   * Returns the meta object for the containment reference list '{@link com.zenika.aicdsl.Dsl#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.zenika.aicdsl.Dsl#getElements()
   * @see #getDsl()
   * @generated
   */
  EReference getDsl_Elements();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see com.zenika.aicdsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see com.zenika.aicdsl.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Feature#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see com.zenika.aicdsl.Feature#getTitle()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Title();

  /**
   * Returns the meta object for the containment reference list '{@link com.zenika.aicdsl.Feature#getScenarios <em>Scenarios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scenarios</em>'.
   * @see com.zenika.aicdsl.Feature#getScenarios()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Scenarios();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Scenario <em>Scenario</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scenario</em>'.
   * @see com.zenika.aicdsl.Scenario
   * @generated
   */
  EClass getScenario();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Scenario#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see com.zenika.aicdsl.Scenario#getTitle()
   * @see #getScenario()
   * @generated
   */
  EAttribute getScenario_Title();

  /**
   * Returns the meta object for the containment reference list '{@link com.zenika.aicdsl.Scenario#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see com.zenika.aicdsl.Scenario#getActions()
   * @see #getScenario()
   * @generated
   */
  EReference getScenario_Actions();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see com.zenika.aicdsl.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see com.zenika.aicdsl.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Sensor#getSensorName <em>Sensor Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sensor Name</em>'.
   * @see com.zenika.aicdsl.Sensor#getSensorName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_SensorName();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Sensor#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.zenika.aicdsl.Sensor#getValue()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Value();

  /**
   * Returns the meta object for the reference '{@link com.zenika.aicdsl.Sensor#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Title</em>'.
   * @see com.zenika.aicdsl.Sensor#getTitle()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Title();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Battery <em>Battery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Battery</em>'.
   * @see com.zenika.aicdsl.Battery
   * @generated
   */
  EClass getBattery();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Battery#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.zenika.aicdsl.Battery#getValue()
   * @see #getBattery()
   * @generated
   */
  EAttribute getBattery_Value();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Gps <em>Gps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gps</em>'.
   * @see com.zenika.aicdsl.Gps
   * @generated
   */
  EClass getGps();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Gps#getLat <em>Lat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lat</em>'.
   * @see com.zenika.aicdsl.Gps#getLat()
   * @see #getGps()
   * @generated
   */
  EAttribute getGps_Lat();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Gps#getLon <em>Lon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lon</em>'.
   * @see com.zenika.aicdsl.Gps#getLon()
   * @see #getGps()
   * @generated
   */
  EAttribute getGps_Lon();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Gps#getAlti <em>Alti</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alti</em>'.
   * @see com.zenika.aicdsl.Gps#getAlti()
   * @see #getGps()
   * @generated
   */
  EAttribute getGps_Alti();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see com.zenika.aicdsl.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Click#getButtonName <em>Button Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button Name</em>'.
   * @see com.zenika.aicdsl.Click#getButtonName()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_ButtonName();

  /**
   * Returns the meta object for class '{@link com.zenika.aicdsl.Run <em>Run</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Run</em>'.
   * @see com.zenika.aicdsl.Run
   * @generated
   */
  EClass getRun();

  /**
   * Returns the meta object for the attribute '{@link com.zenika.aicdsl.Run#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Name</em>'.
   * @see com.zenika.aicdsl.Run#getAppName()
   * @see #getRun()
   * @generated
   */
  EAttribute getRun_AppName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AicdslFactory getAicdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.DslImpl <em>Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.DslImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getDsl()
     * @generated
     */
    EClass DSL = eINSTANCE.getDsl();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DSL__ELEMENTS = eINSTANCE.getDsl_Elements();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.TypeImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.FeatureImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__TITLE = eINSTANCE.getFeature_Title();

    /**
     * The meta object literal for the '<em><b>Scenarios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__SCENARIOS = eINSTANCE.getFeature_Scenarios();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.ScenarioImpl <em>Scenario</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.ScenarioImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getScenario()
     * @generated
     */
    EClass SCENARIO = eINSTANCE.getScenario();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCENARIO__TITLE = eINSTANCE.getScenario_Title();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCENARIO__ACTIONS = eINSTANCE.getScenario_Actions();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.ActionImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.SensorImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Sensor Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__SENSOR_NAME = eINSTANCE.getSensor_SensorName();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__VALUE = eINSTANCE.getSensor_Value();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__TITLE = eINSTANCE.getSensor_Title();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.BatteryImpl <em>Battery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.BatteryImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getBattery()
     * @generated
     */
    EClass BATTERY = eINSTANCE.getBattery();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BATTERY__VALUE = eINSTANCE.getBattery_Value();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.GpsImpl <em>Gps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.GpsImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getGps()
     * @generated
     */
    EClass GPS = eINSTANCE.getGps();

    /**
     * The meta object literal for the '<em><b>Lat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GPS__LAT = eINSTANCE.getGps_Lat();

    /**
     * The meta object literal for the '<em><b>Lon</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GPS__LON = eINSTANCE.getGps_Lon();

    /**
     * The meta object literal for the '<em><b>Alti</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GPS__ALTI = eINSTANCE.getGps_Alti();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.ClickImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Button Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__BUTTON_NAME = eINSTANCE.getClick_ButtonName();

    /**
     * The meta object literal for the '{@link com.zenika.aicdsl.impl.RunImpl <em>Run</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zenika.aicdsl.impl.RunImpl
     * @see com.zenika.aicdsl.impl.AicdslPackageImpl#getRun()
     * @generated
     */
    EClass RUN = eINSTANCE.getRun();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RUN__APP_NAME = eINSTANCE.getRun_AppName();

  }

} //AicdslPackage
