/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.Click#getButtonName <em>Button Name</em>}</li>
 * </ul>
 *
 * @see com.zenika.aicdsl.AicdslPackage#getClick()
 * @model
 * @generated
 */
public interface Click extends Action
{
  /**
   * Returns the value of the '<em><b>Button Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Button Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button Name</em>' attribute.
   * @see #setButtonName(String)
   * @see com.zenika.aicdsl.AicdslPackage#getClick_ButtonName()
   * @model
   * @generated
   */
  String getButtonName();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Click#getButtonName <em>Button Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Button Name</em>' attribute.
   * @see #getButtonName()
   * @generated
   */
  void setButtonName(String value);

} // Click
