/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gps</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.Gps#getLat <em>Lat</em>}</li>
 *   <li>{@link com.zenika.aicdsl.Gps#getLon <em>Lon</em>}</li>
 *   <li>{@link com.zenika.aicdsl.Gps#getAlti <em>Alti</em>}</li>
 * </ul>
 *
 * @see com.zenika.aicdsl.AicdslPackage#getGps()
 * @model
 * @generated
 */
public interface Gps extends Action
{
  /**
   * Returns the value of the '<em><b>Lat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lat</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lat</em>' attribute.
   * @see #setLat(float)
   * @see com.zenika.aicdsl.AicdslPackage#getGps_Lat()
   * @model
   * @generated
   */
  float getLat();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Gps#getLat <em>Lat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lat</em>' attribute.
   * @see #getLat()
   * @generated
   */
  void setLat(float value);

  /**
   * Returns the value of the '<em><b>Lon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lon</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lon</em>' attribute.
   * @see #setLon(float)
   * @see com.zenika.aicdsl.AicdslPackage#getGps_Lon()
   * @model
   * @generated
   */
  float getLon();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Gps#getLon <em>Lon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lon</em>' attribute.
   * @see #getLon()
   * @generated
   */
  void setLon(float value);

  /**
   * Returns the value of the '<em><b>Alti</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alti</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alti</em>' attribute.
   * @see #setAlti(float)
   * @see com.zenika.aicdsl.AicdslPackage#getGps_Alti()
   * @model
   * @generated
   */
  float getAlti();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Gps#getAlti <em>Alti</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alti</em>' attribute.
   * @see #getAlti()
   * @generated
   */
  void setAlti(float value);

} // Gps
