/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.Run#getAppName <em>App Name</em>}</li>
 * </ul>
 *
 * @see com.zenika.aicdsl.AicdslPackage#getRun()
 * @model
 * @generated
 */
public interface Run extends Action
{
  /**
   * Returns the value of the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>App Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Name</em>' attribute.
   * @see #setAppName(String)
   * @see com.zenika.aicdsl.AicdslPackage#getRun_AppName()
   * @model
   * @generated
   */
  String getAppName();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Run#getAppName <em>App Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Name</em>' attribute.
   * @see #getAppName()
   * @generated
   */
  void setAppName(String value);

} // Run
