/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.Scenario#getTitle <em>Title</em>}</li>
 *   <li>{@link com.zenika.aicdsl.Scenario#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see com.zenika.aicdsl.AicdslPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see com.zenika.aicdsl.AicdslPackage#getScenario_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Scenario#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link com.zenika.aicdsl.Action}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see com.zenika.aicdsl.AicdslPackage#getScenario_Actions()
   * @model containment="true"
   * @generated
   */
  EList<Action> getActions();

} // Scenario
