/**
 * generated by Xtext 2.10.0
 */
package com.zenika.aicdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zenika.aicdsl.Sensor#getSensorName <em>Sensor Name</em>}</li>
 *   <li>{@link com.zenika.aicdsl.Sensor#getValue <em>Value</em>}</li>
 *   <li>{@link com.zenika.aicdsl.Sensor#getTitle <em>Title</em>}</li>
 * </ul>
 *
 * @see com.zenika.aicdsl.AicdslPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends Action
{
  /**
   * Returns the value of the '<em><b>Sensor Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sensor Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor Name</em>' attribute.
   * @see #setSensorName(String)
   * @see com.zenika.aicdsl.AicdslPackage#getSensor_SensorName()
   * @model
   * @generated
   */
  String getSensorName();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Sensor#getSensorName <em>Sensor Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor Name</em>' attribute.
   * @see #getSensorName()
   * @generated
   */
  void setSensorName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see com.zenika.aicdsl.AicdslPackage#getSensor_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Sensor#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' reference.
   * @see #setTitle(Scenario)
   * @see com.zenika.aicdsl.AicdslPackage#getSensor_Title()
   * @model
   * @generated
   */
  Scenario getTitle();

  /**
   * Sets the value of the '{@link com.zenika.aicdsl.Sensor#getTitle <em>Title</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Scenario value);

} // Sensor
